### ISSUE TITLE
AI SVS mode not working

### ISSUE THREAD

**Issue by ghost** [rperez-rosario/HPCalculatorChess#1]
When I start a game of chess using the SVS mode, the screen flickers and nothing happens, as shown in the video. I understand that it is slow, but I've let it run for thirty minutes and nothing changes. Am I using it correctly?

https://photos.app.goo.gl/fmzdAVTPfxycysF19

**Comment by rperez-rosario** [comment]
Hi. 

If you take a look at the source code, you will find that a step-value search function is present but not implemented at this time. I don't have plans to implement it anytime soon. In its present state the program allows human vs. human play only. You are free to implement it using the rest of the code facilities as a framework. I recommend the following text book to this end: 

Artificial Intelligence, A Modern Approach (Russell and Norvig.)

https://www.amazon.com/Artificial-Intelligence-Approach-Stuart-Russell/dp/9356063575/ref=sr_1_1?crid=373E7MQ76JZ2Y&keywords=artificial+intelligence+a+modern+approach&qid=1699846842&sprefix=artificial+intellig%2Caps%2C115&sr=8-1

You may want to look at state-space search algorithms descriptions in particular.

Best regards.

Rafael
